"""user status: add refresh_revoked_at

Revision ID: 0caf26a44aa5
Revises: b3c7724197c1
Create Date: 2025-08-08 23:20:20.342351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0caf26a44aa5'
down_revision: Union[str, Sequence[str], None] = 'b3c7724197c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_revoked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_revoked_at')
    # ### end Alembic commands ###
