"""add unique constraint on auth_providers (provider_name, provider_user_id)

Revision ID: 31b9e8de4296
Revises: 2189bd17b44b
Create Date: 2025-08-08 16:04:12.837841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b9e8de4296'
down_revision: Union[str, Sequence[str], None] = '2189bd17b44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
