"""update table blacklistedtoken_change_string_into_text

Revision ID: 6630c35affae
Revises: 2265109d31ea
Create Date: 2025-08-18 07:55:39.004073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6630c35affae'
down_revision: Union[str, Sequence[str], None] = '2265109d31ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
