"""fix relationship between User and AuthProvider

Revision ID: 730c5b601c9f
Revises: beea60e274cb
Create Date: 2025-08-06 07:22:37.829551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730c5b601c9f'
down_revision: Union[str, Sequence[str], None] = 'beea60e274cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_providers_user_id_fkey'), 'auth_providers', type_='foreignkey')
    op.create_foreign_key(None, 'auth_providers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_providers', type_='foreignkey')
    op.create_foreign_key(op.f('auth_providers_user_id_fkey'), 'auth_providers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
