"""google oauth support (no schema change)

Revision ID: 953b8c22cbc3
Revises: 31b9e8de4296
Create Date: 2025-08-08 16:57:30.131344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953b8c22cbc3'
down_revision: Union[str, Sequence[str], None] = '31b9e8de4296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
